export const RED = '#A14545';
export const GRAY = '#626262';
export const GREEN = '#108A2D';
export const WHITE = '#FFFFFF';
export const CONNECTION_ERROR = 'Интернэт холболтоо шалгана уу.';
export const NODATA = 'Өгөгдөл олдсонгүй';
export const LOGIN_AGAIN = 'Системд дахин нэвтрэнэ үү!';
export const LOGIN_ERROR = 'Хэрэглэгчийн нэр нууц үг буруу байна.';
export const LOADING = 'Уншиж байна...';
